pipeline {
    agent any

    environment {
        IMAGE = "alyyasser10/devops-project-8:latest"
    }

    stages {
					
        stage('Checkout') {
            steps {
                git 'http://github.com/AliYasser2003/Devops_project-8_End-to-End-DevOps-Pipeline-System'
            }
        }

        stage('Build Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE .'
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $IMAGE'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'helm upgrade my-app ./helm/my-app'
            }
        }
    }
}
